services:
  auth-api:
    build: ./auth-api
    ports:
      - "4000:4000"

  iot:
    build: ./iot
    ports:
      - "5174:5174"
    depends_on:
      - auth-api

  finance:
    build: ./finance
    ports:
      - "5175:5175"
    depends_on:
      - auth-api

  kurz-panel:
    build: ./kurz-panel
    ports:
      - "5173:5173"
    depends_on:
      - auth-api
      - iot
      - finance
